apiVersion: v1
kind: Secret
metadata:
  name: p-secret-fb
type: Opaque
data:
  DB_HOST: ZGJzb3NtZWQuY2cybHNzbnBncjV1LmFwLXNvdXRoZWFzdC0xLnJkcy5hbWF6b25hd3MuY29t
  DB_USER: YWRtaW4=
  DB_PASS: UzBtZXRoMW5nQ2lsc3k=

